#!/bin/bash

set -euxo pipefail

# build platform-specific Docker images
docker build -f Dockerfile.amd64 -t __DOCKER_HUB_USERNAME__/__CONTAINER__:latest-amd64 .
docker build -f Dockerfile.arm32v7 -t __DOCKER_HUB_USERNAME__/__CONTAINER__:latest-arm32v7 .
docker build -f Dockerfile.arm64v8 -t __DOCKER_HUB_USERNAME__/__CONTAINER__:latest-arm64v8 .

